[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"

[[plugins]]
package = "netlify-plugin-amp-server-side-rendering"
